#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT_DIR/build/sshl​​inux"
ROOTFS="$OUT_DIR/rootfs"
RAMDISK_DIR="$ROOT_DIR/sshramdisk"

FEDORA_RELEASE="${FEDORA_RELEASE:-44}"
ARCH="${ARCH:-aarch64}"

rm -rf "$OUT_DIR"
mkdir -p "$ROOTFS" "$RAMDISK_DIR"

command -v dnf >/dev/null 2>&1 || {
    echo "[!] dnf is required to build the Fedora payload."
    exit 1
}

command -v cpio >/dev/null 2>&1 || {
    echo "[!] cpio is required."
    exit 1
}

command -v gzip >/dev/null 2>&1 || {
    echo "[!] gzip is required."
    exit 1
}

echo "[*] Building Fedora ${FEDORA_RELEASE} ${ARCH} SSHLinux userspace"

# The GitHub runner is normally x86_64. We only download target-arch RPMs here;
# no target binaries are executed during the rootfs construction.
sudo dnf -y --releasever="$FEDORA_RELEASE" \
    --forcearch="$ARCH" \
    --installroot="$ROOTFS" \
    --setopt=install_weak_deps=False \
    --setopt=keepcache=False \
    --setopt=tsflags=nodocs \
    install \
        bash \
        coreutils \
        util-linux \
        iproute \
        iputils \
        procps-ng \
        kmod \
        openssh-clients \
        openssh-server \
        dropbear \
        ca-certificates \
        curl \
        wget \
        busybox \
        findutils \
        grep \
        sed \
        gawk \
        tar \
        gzip \
        xz \
        nano

mkdir -p "$ROOTFS/etc/ssh" "$ROOTFS/etc/systemd/system" "$ROOTFS/etc/dropbear" \
         "$ROOTFS/root" "$ROOTFS/run" "$ROOTFS/tmp" "$ROOTFS/dev" "$ROOTFS/proc" \
         "$ROOTFS/sys" "$ROOTFS/mnt" "$ROOTFS/usr/local/bin"

cat > "$ROOTFS/etc/os-release" <<EOF
NAME="SSHLinux Fedora"
ID=fedora
VERSION="${FEDORA_RELEASE}"
VERSION_ID="${FEDORA_RELEASE}"
PRETTY_NAME="SSHLinux Fedora ${FEDORA_RELEASE}"
EOF

cat > "$ROOTFS/usr/local/bin/sshl​​inux-init" <<'EOF'
#!/bin/sh
set -eu

mountpoint -q /proc || mount -t proc proc /proc || true
mountpoint -q /sys  || mount -t sysfs sysfs /sys || true
mountpoint -q /dev  || mount -t devtmpfs devtmpfs /dev || true
mountpoint -q /run  || mount -t tmpfs tmpfs /run || true

mkdir -p /run/sshl​​inux /tmp /root
chmod 1777 /tmp

if command -v dropbear >/dev/null 2>&1; then
    mkdir -p /etc/dropbear
    if [ ! -f /etc/dropbear/dropbear_rsa_host_key ]; then
        dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key >/dev/null 2>&1 || true
    fi
    if [ ! -f /etc/dropbear/dropbear_ecdsa_host_key ]; then
        dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key >/dev/null 2>&1 || true
    fi
    exec dropbear -R -E -F -p 22
fi

exec /bin/sh
EOF
chmod 0755 "$ROOTFS/usr/local/bin/sshl​​inux-init"

# Minimal SSH configuration; authentication policy can be replaced by the
# device-side ramdisk integration without changing this payload builder.
cat > "$ROOTFS/etc/dropbear/dropbear.conf" <<'EOF'
# SSHLinux Dropbear configuration placeholder.
# Runtime options are passed by sshl​​inux-init.
EOF

printf '%s\n' "$FEDORA_RELEASE" > "$OUT_DIR/version.txt"
printf '%s\n' "$ARCH" > "$OUT_DIR/arch.txt"

printf '%s\0' . | (cd "$ROOTFS" && cpio --null -o -H newc 2>/dev/null | gzip -9 > "$OUT_DIR/payload.cpio.gz")

cp "$OUT_DIR/payload.cpio.gz" "$RAMDISK_DIR/fedora-payload.cpio.gz"
cat > "$RAMDISK_DIR/README" <<EOF
This directory contains the Fedora SSHLinux userspace payload produced by CI.

The Apple boot-chain components (iBSS/iBEC/ramdisk.img4/devicetree/kernelcache/
trustcache) are device/version specific and are not generated by this generic
Fedora userspace build.

Fedora release: ${FEDORA_RELEASE}
Architecture: ${ARCH}
EOF

echo "[*] Payload created: $OUT_DIR/payload.cpio.gz"
echo "[*] Installed to:    $RAMDISK_DIR/fedora-payload.cpio.gz"
